type SummaryCardProps = {
  summary: string;
};

export default function SummaryCard({ summary }: SummaryCardProps) {
  return (
    <div className="max-w-4xl mx-auto mt-10 rounded-3xl border border-violet-500/20 bg-zinc-900/70 backdrop-blur-xl p-8 transition-all duration-300 hover:-translate-y-1 shadow-2xl shadow-violet-900/20">

      <div className="flex items-center justify-between">

        <div>
          <h2 className="text-3xl font-bold text-white">
            📝 AI Summary
          </h2>

          <p className="text-zinc-400 mt-2">
            Generated by Gemini AI
          </p>
        </div>

        <span className="rounded-full bg-violet-500/20 border border-violet-500/30 px-4 py-2 text-violet-300 text-sm">
          {summary ? "Completed" : "Waiting"}
        </span>

      </div>

      <div className="mt-8 rounded-2xl bg-zinc-800/60 p-6 min-h-[220px]">

        <p className="text-zinc-300 leading-8 whitespace-pre-wrap">

          {summary
            ? summary
            : "Upload a PDF and click '✨ Summarize PDF' to generate an AI summary."}

        </p>

      </div>

      <div className="flex flex-wrap gap-4 mt-10">

        <button
          onClick={() => navigator.clipboard.writeText(summary)}
          disabled={!summary}
          className="bg-violet-600 hover:bg-violet-700 disabled:opacity-50 active:scale-95 transition-all duration-300 px-6 py-3 rounded-xl font-semibold shadow-lg shadow-violet-700/30"
        >
          📋 Copy Summary
        </button>

        <button
          disabled={!summary}
          className="bg-green-600 hover:bg-green-700 disabled:opacity-50 active:scale-95 transition-all duration-300 px-6 py-3 rounded-xl font-semibold"
        >
          ⬇ Download
        </button>

        <button
          onClick={() => window.location.reload()}
          className="bg-zinc-800 hover:bg-zinc-700 active:scale-95 transition-all duration-300 px-6 py-3 rounded-xl font-semibold border border-zinc-700"
        >
          🔄 New PDF
        </button>

      </div>

    </div>
  );
}