"use client";

type SummaryCardProps = {
  summary: string;
};

export default function SummaryCard({ summary }: SummaryCardProps) {
  const downloadSummary = () => {
    if (!summary) return;

    const blob = new Blob([summary], {
      type: "text/plain;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");

    link.href = url;
    link.download = "smart-study-notes.txt";
    document.body.appendChild(link);
    link.click();

    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-4xl mx-auto mt-8 sm:mt-10 rounded-3xl border border-violet-500/20 bg-zinc-900/70 backdrop-blur-xl p-4 sm:p-6 md:p-8 transition-all duration-300 hover:-translate-y-1 shadow-2xl shadow-violet-900/20">

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">

        <div className="min-w-0">
          <h2 className="text-2xl sm:text-3xl font-bold text-white">
            📝 AI Summary
          </h2>

          <p className="text-zinc-400 mt-2 text-sm sm:text-base">
            Generated by Gemini AI
          </p>
        </div>

        <span className="self-start sm:self-auto shrink-0 rounded-full bg-violet-500/20 border border-violet-500/30 px-4 py-2 text-violet-300 text-sm">
          {summary ? "Completed" : "Waiting"}
        </span>

      </div>

      {/* Summary Content */}
      <div className="mt-6 sm:mt-8 rounded-2xl bg-zinc-800/60 p-4 sm:p-6 min-h-[180px] sm:min-h-[220px] overflow-hidden">

        <p className="text-zinc-300 leading-7 sm:leading-8 whitespace-pre-wrap break-words text-sm sm:text-base">
          {summary
            ? summary
            : "Upload a PDF and click '✨ Summarize PDF' to generate an AI summary."}
        </p>

      </div>

      {/* Buttons */}
      <div className="grid grid-cols-1 sm:flex sm:flex-wrap gap-3 sm:gap-4 mt-6 sm:mt-10">

        <button
          type="button"
          onClick={() => navigator.clipboard.writeText(summary)}
          disabled={!summary}
          className="w-full sm:w-auto bg-violet-600 hover:bg-violet-700 disabled:opacity-50 active:scale-95 transition-all duration-300 px-6 py-3 rounded-xl font-semibold shadow-lg shadow-violet-700/30"
        >
          📋 Copy Summary
        </button>

        <button
          type="button"
          onClick={downloadSummary}
          disabled={!summary}
          className="w-full sm:w-auto bg-green-600 hover:bg-green-700 disabled:opacity-50 active:scale-95 transition-all duration-300 px-6 py-3 rounded-xl font-semibold"
        >
          ⬇ Download
        </button>

        <button
          type="button"
          onClick={() => window.location.reload()}
          className="w-full sm:w-auto bg-zinc-800 hover:bg-zinc-700 active:scale-95 transition-all duration-300 px-6 py-3 rounded-xl font-semibold border border-zinc-700"
        >
          🔄 New PDF
        </button>

      </div>

    </div>
  );
}